/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject;

/**
 *
 * @author hp
 */
import java.sql.*;
import javax.swing.JOptionPane;
import oracle.jdbc.driver.*;

public class RegistrationAccountant extends javax.swing.JFrame {

    /**
     * Creates new form studentResult
     */
     Connection cnn;
    Statement st;
    ResultSet rs,rs1;
    String gen;
    int count=0;
    public RegistrationAccountant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t3 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel2.setText("ACCOUNTANT REGISTRATION");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 0, 530, 80);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("NAME");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 90, 60, 30);
        jPanel1.add(t1);
        t1.setBounds(130, 90, 200, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("USER ID");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 130, 80, 30);
        jPanel1.add(t2);
        t2.setBounds(130, 130, 200, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("PASSWORD");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 170, 100, 30);
        jPanel1.add(t3);
        t3.setBounds(130, 170, 180, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("CONTACT");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(380, 90, 90, 30);
        jPanel1.add(t4);
        t4.setBounds(480, 90, 200, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("EMAIL");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 210, 60, 30);
        jPanel1.add(t6);
        t6.setBounds(130, 210, 480, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("ADHARCARD NUMBER");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 250, 190, 30);
        jPanel1.add(t7);
        t7.setBounds(210, 250, 400, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("ADDRESS");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 290, 80, 30);
        jPanel1.add(t8);
        t8.setBounds(130, 290, 560, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(150, 340, 120, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("YEAR OF JOINING");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(360, 130, 150, 30);
        jPanel1.add(t5);
        t5.setBounds(520, 130, 160, 30);

        jButton2.setBackground(new java.awt.Color(255, 255, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 340, 120, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("GENDER");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(390, 170, 90, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("MALE");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(490, 170, 70, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("FEMALE");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(570, 170, 93, 23);

        jButton3.setBackground(new java.awt.Color(255, 255, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setText("SEARCH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(280, 340, 120, 40);

        jButton4.setBackground(new java.awt.Color(255, 255, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(410, 340, 120, 40);

        jButton5.setBackground(new java.awt.Color(255, 255, 102));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton5.setText("DELETE RECORD");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(540, 340, 150, 40);

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(310, 170, 20, 30);

        jButton7.setBackground(new java.awt.Color(255, 255, 102));
        jButton7.setText("back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(10, 10, 55, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Purple-Shaded-Plain-Background1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -100, 750, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
             DriverManager.registerDriver(new OracleDriver());
      Connection cnn = DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","wisdom22");
      
      String nm=t1.getText();
      String user=t2.getText();
      String password=t3.getText();
      String cont=t4.getText();
      String year=t5.getText();
      String id=t6.getText();
      String num=t7.getText();
      String addr=t8.getText();
      if(jRadioButton1.isSelected()==true)
      {
          gen="male";
      }
      if(jRadioButton2.isSelected()==true)
      {
          gen="female";
      }
      String f="ACCOUNTANT";
      
       String q2="select * from userids where username='"+user+"'"; 
      st=cnn.createStatement();
      rs=st.executeQuery(q2);
      {
          if(rs.next())
          {
              JOptionPane.showMessageDialog(null, "username already exists");
          }
      }
      
      if(t1.getText().equals("") || t2.getText().equals("") || t3.getText().equals("") ||t4.getText().equals("") ||t5.getText().equals("") ||t6.getText().equals("") ||t7.getText().equals("")||t8.getText().equals("")||(jRadioButton1.isSelected()==false&&jRadioButton2.isSelected()==false ))
      {
       JOptionPane.showMessageDialog(null, "please fill all fields");
      }
      else if(cont.length()!=10)
              {
                  JOptionPane.showMessageDialog(null, "please fill valid contact details");
              }
      else if(num.length()!=12)
      {
           JOptionPane.showMessageDialog(null, "please fill valid adharcard number");
      }
       else if(addr.length()<10)
      {
           JOptionPane.showMessageDialog(null, "please fill complete address as on registered documents");
      }
        else if(id.length()<10)
      {
           JOptionPane.showMessageDialog(null, "please fill valid email address");
      }
      else
      {
      String q="insert into accountantInfo values('"+nm+"','"+cont+"','"+year+"','"+gen+"','"+id+"','"+num+"','"+addr+"')";
      String q1="insert into userids values ('"+f+"','"+user+"','"+password+"')";
      
       st=cnn.createStatement();
       st.executeUpdate(q);
       st.executeUpdate(q1);
       JOptionPane.showMessageDialog(null, "saved");
      }
        } catch (Exception e) {
       
            System.out.print(e);
        
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        t1.setText("");
        t2.setText("");
        t3.setText("");
        t4.setText("");
        t5.setText("");
        t6.setText("");
        t7.setText("");
        t8.setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
          try {
             DriverManager.registerDriver(new OracleDriver());
      Connection cnn = DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","wisdom22");
      
      String nm=t1.getText();
     String user=t2.getText();
      String cont="";
      String gen="";
      String year="";
      String num="";
      String password="";
      String email="";
      String addr="";
      
      String q="select * from accountantInfo where name='"+nm+"'";
      String q1="select * from userids where username='"+user+"'";
      st=cnn.createStatement();
      rs=st.executeQuery(q);
    
      if(rs.next())
      {
          cont=rs.getString("contact");
          gen=rs.getString("gender");
          year=rs.getString("year");
          num=rs.getString("adharno");
          
          email=rs.getString("email");
          addr=rs.getString("address");
          t4.setText(cont);
          t7.setText(num); 
         
          t6.setText(email);
          t8.setText(addr); 
          t5.setText(year);
          if(gen.equals("male"))
      {
          jRadioButton1.setSelected(true);
      }
      if(gen.equals("female"))
      {
          jRadioButton2.setSelected(true);
      }
      }
      
       rs1=st.executeQuery(q1);
       if(rs1.next())
       {
           password=rs1.getString("password");
            t3.setText(password);
       }
     
      else
      {
          JOptionPane.showMessageDialog(null,"record not found");
      }
        } catch (Exception e) {
            System.out.print(e);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
         try {
            DriverManager.registerDriver(new OracleDriver());
      Connection cnn = DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","wisdom22");
      
      String nm=t1.getText();
      String user=t2.getText();
      String password=t3.getText();
      String addr=t8.getText();
      String cont=t4.getText();
      String id=t6.getText();
      String num=t7.getText();
      String year=t5.getText();
       if(jRadioButton1.isSelected()==true)
     {
          gen="male";
     }
     if(jRadioButton2.isSelected()==true)
     {
         gen="female";
     }
     
      String f="ACCOUNTANT"; 
      String q="update accountantInfo set contact='"+cont+"',year='"+year+"',gender='"+gen+"',email='"+id+"',adharno='"+num+"',address='"+addr+"' where name='"+nm+"'";
      String q1="update userids set usertype='"+f+"',password='"+password+"' where username='"+user+"'";
       st=cnn.createStatement();
       st.executeUpdate(q);
       st.executeQuery(q1);
       JOptionPane.showMessageDialog(null, "updated");
      
        
        } catch (Exception e) {
            System.out.print(e);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
          try {
             DriverManager.registerDriver(new OracleDriver());
      Connection cnn = DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","wisdom22");
      String nm=t1.getText();
       String user=t2.getText();
       String q="delete from accountantInfo where name='"+nm+"'";
       String q1="delete from userids where username='"+user+"'";
        st=cnn.createStatement();
       st.executeUpdate(q);
      st.executeQuery(q1);
       JOptionPane.showMessageDialog(null, "deleted");
      
       
        } catch (Exception e) {
           System.out.print(e);
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
         count++;
        if(count%2==1)
        {
            t3.setEchoChar((char)0);
        }
        else
        {
            t3.setEchoChar('*');
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        admin a=new admin();
        a.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationAccountant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationAccountant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationAccountant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationAccountant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationAccountant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JPasswordField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    // End of variables declaration//GEN-END:variables
}
