/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject;

/**
 *
 * @author hp
 */
import java.sql.*;
import javax.swing.JOptionPane;
import oracle.jdbc.driver.*;

public class salarySlip extends javax.swing.JFrame {

    /**
     * Creates new form viewSalary
     */
    
   
    Connection cnn;
    Statement st;
    ResultSet rs,rs1;
    String mode;
     public int count;
    public salarySlip() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        t10 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        t11 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        t12 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        t13 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        t14 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        t15 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        t17 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        t18 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        t19 = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        t16 = new javax.swing.JTextField();
        btn2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        jLabel2.setText("SALARY SLIP");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 10, 390, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("User id");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 80, 60, 30);
        jPanel1.add(t1);
        t1.setBounds(150, 80, 180, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 120, 50, 30);
        jPanel1.add(t2);
        t2.setBounds(150, 120, 180, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Bank Name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 200, 90, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Account no.");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 240, 100, 30);
        jPanel1.add(t3);
        t3.setBounds(150, 200, 180, 30);
        jPanel1.add(t4);
        t4.setBounds(150, 240, 180, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Month");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(440, 120, 60, 30);
        jPanel1.add(t5);
        t5.setBounds(510, 80, 180, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Total working days");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(350, 160, 150, 30);

        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });
        jPanel1.add(t6);
        t6.setBounds(510, 160, 180, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Leaves");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(450, 200, 53, 30);
        jPanel1.add(t7);
        t7.setBounds(510, 200, 180, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Total days worked");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(360, 240, 150, 30);
        jPanel1.add(t8);
        t8.setBounds(510, 240, 180, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel13.setText("EARNINGS");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(190, 280, 110, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel14.setText("DEDUCTIONS");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(500, 280, 130, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Basic");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(120, 320, 50, 30);

        t9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t9ActionPerformed(evt);
            }
        });
        jPanel1.add(t9);
        t9.setBounds(180, 320, 170, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Special Allowance");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(30, 360, 140, 30);
        jPanel1.add(t10);
        t10.setBounds(180, 360, 170, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Conveyance");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(70, 400, 100, 30);
        jPanel1.add(t11);
        t11.setBounds(180, 400, 170, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Bonus");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(110, 440, 60, 30);
        jPanel1.add(t12);
        t12.setBounds(180, 440, 170, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Provident Fund");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(380, 320, 120, 30);
        jPanel1.add(t13);
        t13.setBounds(510, 320, 180, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Professional Tax");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(370, 360, 130, 30);
        jPanel1.add(t14);
        t14.setBounds(510, 360, 180, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Income Tax");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(410, 400, 100, 30);
        jPanel1.add(t15);
        t15.setBounds(510, 400, 180, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel22.setText("gross earnings");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(70, 480, 110, 30);
        jPanel1.add(t17);
        t17.setBounds(180, 480, 170, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel23.setText("gross deductions");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(390, 480, 120, 30);
        jPanel1.add(t18);
        t18.setBounds(520, 480, 170, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("NET PAY");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(130, 520, 80, 20);
        jPanel1.add(t19);
        t19.setBounds(220, 520, 160, 30);

        btn1.setBackground(new java.awt.Color(255, 153, 255));
        btn1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn1.setText("SEARCH");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1);
        btn1.setBounds(410, 520, 110, 30);

        jButton2.setBackground(new java.awt.Color(255, 153, 255));
        jButton2.setText("back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 10, 80, 23);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("Slip no.");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(440, 80, 70, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "january", "february", "march", "april", "may", "june", "july", "august", "september", "october", "november", "december" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(510, 120, 180, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("CHECK");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(150, 160, 80, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("BANK");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(250, 160, 70, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Mode");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 160, 50, 20);

        jLabel11.setText("# fill userid,name,mode,month and leaves");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(270, 60, 250, 14);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("Leaves");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(450, 440, 60, 30);
        jPanel1.add(t16);
        t16.setBounds(510, 440, 180, 30);

        btn2.setBackground(new java.awt.Color(255, 153, 255));
        btn2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn2.setText("SUBMIT");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2);
        btn2.setBounds(550, 520, 110, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/courses backg.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-10, 0, 910, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        faculty f=new faculty();
        f.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t9ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        
        try{
            
              DriverManager.registerDriver(new OracleDriver());
      Connection cnn = DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","wisdom22");
       
        count++;
        
        String user=t1.getText();
        String leaves=t7.getText();
        if(jRadioButton1.isSelected()==true)
        {
            String mode="check";
        }
         if(jRadioButton2.isSelected()==true)
        {
            String mode="bank";
        }
         String month=jComboBox1.getSelectedItem().toString();
         if(month.equals("january")||month.equals("march")||month.equals("may")||month.equals("july")||month.equals("august")||month.equals("october")||month.equals("december"))
         {
             t6.setText("31");
              String t=Double.toString(Double.parseDouble("31")-Double.parseDouble(t7.getText()));
              t8.setText(t);
         }
         else
         {
             t6.setText("30");
              String t=Double.toString(Double.parseDouble("30")-Double.parseDouble(t7.getText()));
              t8.setText(t);
         }
        
        
        t5.setText(month+count);
        t15.setText("2000");
        t14.setText("200");
        t10.setText("1000");
        t11.setText("500");
       
        String sal="";
        String bonus="";
        String q="select * from salary where userid='"+user+"'";
        
        st=cnn.createStatement();
        rs=st.executeQuery(q);
        if(rs.next())
        {
            sal=rs.getString("basicsalary");
            bonus=rs.getString("bonus");
            t9.setText(sal);
            t12.setText(bonus);
        
        double l=(Double.parseDouble(t9.getText())*Double.parseDouble(t7.getText()))/Double.parseDouble(t6.getText());
        String lv=Double.toString(l);
        t16.setText(lv);
        String p=Double.toString(Double.parseDouble(sal)*0.12);
        t13.setText(p);
        String ge=Double.toString(Double.parseDouble(sal)+Double.parseDouble("1000")+Double.parseDouble("500")+Double.parseDouble(bonus));
        t17.setText(ge);
         String gd=Double.toString(Double.parseDouble(p)+Double.parseDouble("200")+Double.parseDouble("2000")+Double.parseDouble(lv));
        t18.setText(gd);
        String n=Double.toString(((Double.parseDouble(sal)+Double.parseDouble("1000")+Double.parseDouble("500")+Double.parseDouble(bonus)))-((Double.parseDouble(p)+Double.parseDouble("200")+Double.parseDouble("2000")+Double.parseDouble(lv))));
       t19.setText(n);
        }
        
        String nm=t2.getText();
        String bank="";
        String acc="";
        String q1="select * from facultyInfo where name='"+user+"'";
        st=cnn.createStatement();
        rs1=st.executeQuery(q1);
        if(rs1.next())
        {
            
            bank=rs1.getString("bankname");
            acc=rs1.getString("account");
          
            t3.setText(bank);
            t4.setText(acc);
        }
        
        }
        catch(Exception e){
            System.out.print(e);
        }
        
        
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        
        try {
            
               DriverManager.registerDriver(new OracleDriver());
      Connection cnn = DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","wisdom22");
      
      String user=t1.getText();
      if(jRadioButton1.isSelected()==true)
      {
       mode="check";
              }     
      if(jRadioButton2.isSelected()==true)
      {
       mode="bank";
              }     
      
      String acc=t4.getText();
      String pay=t19.getText();
      String slipno=t5.getText();
      String present=t8.getText();
      String absent=t7.getText();
      
      String q="insert into salaryRecord values('"+user+"','"+mode+"','"+acc+"','"+pay+"','"+slipno+"','"+present+"','"+absent+"')";
      st=cnn.createStatement();
      st.executeUpdate(q);
      JOptionPane.showMessageDialog(null,"saved");
      
      
        } catch (Exception e) 
        {
            System.out.print(e);            
        }
        
    }//GEN-LAST:event_btn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salarySlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salarySlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salarySlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salarySlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salarySlip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t12;
    private javax.swing.JTextField t13;
    private javax.swing.JTextField t14;
    private javax.swing.JTextField t15;
    private javax.swing.JTextField t16;
    private javax.swing.JTextField t17;
    private javax.swing.JTextField t18;
    private javax.swing.JTextField t19;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
