/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject;

/**
 *
 * @author hp
 */
import java.sql.*;
import javax.swing.JOptionPane;
import oracle.jdbc.driver.*;

public class signupfaculty extends javax.swing.JFrame {

    /**
     * Creates new form signupfaculty
     */
    Connection cnn;
    Statement st;
    ResultSet rs,rs1;
    int count=0;
    public signupfaculty() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        t3 = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        t7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("FACULTY REGISTRATION");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 10, 480, 50);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel3.setText("NAME");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 80, 60, 30);
        jPanel1.add(t1);
        t1.setBounds(120, 80, 170, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("DEPARTMENT");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 120, 130, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("QUALIFICATION");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 160, 140, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("ADDRESS");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 240, 80, 30);
        jPanel1.add(t4);
        t4.setBounds(120, 240, 450, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("CONTACT");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 200, 80, 30);
        jPanel1.add(t5);
        t5.setBounds(120, 200, 190, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("EMAIL");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 280, 70, 30);
        jPanel1.add(t6);
        t6.setBounds(120, 280, 450, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("ADHARCARD NUMBER");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 320, 190, 20);

        b1.setBackground(new java.awt.Color(255, 255, 0));
        b1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        b1.setText("SUBMIT");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(120, 370, 110, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("USER ID");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(320, 80, 70, 30);
        jPanel1.add(t2);
        t2.setBounds(400, 80, 170, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("PASSWORD");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(300, 120, 100, 30);
        jPanel1.add(t3);
        t3.setBounds(400, 120, 150, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Btech", "Phd", "Mtech", "B.Sc", "M.Sc" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(150, 130, 140, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phd", "Btech", "Mtech" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(170, 170, 120, 20);
        jPanel1.add(t7);
        t7.setBounds(220, 320, 350, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 370, 100, 30);

        jButton2.setBackground(new java.awt.Color(255, 255, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(240, 370, 90, 30);

        jButton3.setBackground(new java.awt.Color(255, 255, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(340, 370, 90, 30);

        jButton4.setBackground(new java.awt.Color(255, 255, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton4.setText("DELETE RECORD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(440, 370, 130, 30);

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(550, 120, 20, 30);

        jButton6.setBackground(new java.awt.Color(255, 255, 0));
        jButton6.setText("back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(10, 20, 55, 23);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("BANK");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(340, 160, 50, 30);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(400, 160, 170, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("ACC NO");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(320, 200, 70, 30);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(400, 200, 170, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg 1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 650, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        try {
             DriverManager.registerDriver(new OracleDriver());
      Connection cnn = DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","wisdom22");
      
      String nm=t1.getText();
      String user=t2.getText();
      String password=t3.getText();
      String addr=t4.getText();
      String cont=t5.getText();
      String id=t6.getText();
      String num=t7.getText();
      String dep = jComboBox1.getSelectedItem().toString();
      String qual = jComboBox2.getSelectedItem().toString();
      String f="FACULTY";
      String bank=jTextField1.getText();
      String accno=jTextField2.getText();
      
     
      String q2="select * from userids where username='"+user+"'"; 
      st=cnn.createStatement();
      rs=st.executeQuery(q2);
      {
          if(rs.next())
          {
              JOptionPane.showMessageDialog(null, "username already exists");
          }
      }
       if(t1.getText().equals("") || t2.getText().equals("") || t3.getText().equals("") ||t4.getText().equals("") ||t5.getText().equals("") ||t6.getText().equals("") ||t7.getText().equals("") )
      {
       JOptionPane.showMessageDialog(null, "please fill all fields");
      }
      else if(cont.length()!=10)
              {
                  JOptionPane.showMessageDialog(null, "please fill valid contact details");
              }
      else if(num.length()!=12)
      {
           JOptionPane.showMessageDialog(null, "please fill valid adharcard number");
      }
       else if(addr.length()<10)
      {
           JOptionPane.showMessageDialog(null, "please fill complete address as on registered documents");
      }
        else if(id.length()<10)
      {
           JOptionPane.showMessageDialog(null, "please fill valid email address");
      }
      else
      {
      String q="insert into facultyInfo values('"+nm+"','"+dep+"','"+qual+"','"+addr+"','"+cont+"','"+id+"','"+num+"','"+bank+"','"+accno+"')";
      String q1="insert into userids values ('"+f+"','"+user+"','"+password+"')";
      
       st=cnn.createStatement();
       st.executeUpdate(q);
       st.executeUpdate(q1);
       JOptionPane.showMessageDialog(null, "saved");
      }
        } catch (Exception e) {
       
            System.out.print(e);
        
        }
        
    }//GEN-LAST:event_b1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        t1.setText("");
        t2.setText("");
        t3.setText("");
        t4.setText("");
        t5.setText("");
        t6.setText("");
        t7.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
             DriverManager.registerDriver(new OracleDriver());
      Connection cnn = DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","wisdom22");
      
      String nm=t1.getText();
     String user=t2.getText();
      String cont="";
      String dep="";
      String qual="";
      String num="";
      String pass="";
      String email="";
      String addr="";
      String bank="";
      String accno="";
      
            
      
      String q="select * from facultyInfo where name='"+nm+"'";
      
      st=cnn.createStatement();
      rs=st.executeQuery(q);
     
      if(rs.next())
      {
          cont=rs.getString("contact");
          dep=rs.getString("department");
          qual=rs.getString("qualification");
          num=rs.getString("adharno");
         bank=rs.getString("bankname");
         accno=rs.getString("account");
          email=rs.getString("email");
          addr=rs.getString("address");
          t5.setText(cont);
          t7.setText(num); 
         
          t6.setText(email);
          t4.setText(addr); 
          jComboBox1.setSelectedItem(dep);
          jComboBox2.setSelectedItem(qual);
      }
     
       String q1="select * from userids where username='"+user+"'";
       st=cnn.createStatement();
      rs1=st.executeQuery(q1);
      if(rs1.next())
              {
                  pass=rs1.getString("password"); 
                   t3.setText(pass);
              }

     
      else
      {
          JOptionPane.showMessageDialog(null,"record not found");
      }
        } catch (Exception e) {
            System.out.print(e);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try {
            DriverManager.registerDriver(new OracleDriver());
      Connection cnn = DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","wisdom22");
      
      String nm=t1.getText();
      String user=t2.getText();
      String password=t3.getText();
      String addr=t4.getText();
      String cont=t5.getText();
      String id=t6.getText();
      String num=t7.getText();
      String bank=jTextField1.getText();
      String accno=jTextField2.getText();
      String dep = jComboBox1.getSelectedItem().toString();
      String qual = jComboBox2.getSelectedItem().toString();
      String f="FACULTY"; 
      String q="update facultyInfo set department='"+dep+"',qualification='"+qual+"',address='"+addr+"',contact='"+cont+"',email='"+id+"',adharno='"+num+"',bankname='"+bank+"',account='"+accno+"' where name='"+nm+"'";
      String q1="update userids set usertype='"+f+"',password='"+password+"' where username='"+user+"'";
       st=cnn.createStatement();
       st.executeUpdate(q);
       st.executeQuery(q1);
       JOptionPane.showMessageDialog(null, "updated");
      
        
        } catch (Exception e) {
            System.out.print(e);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          try {
             DriverManager.registerDriver(new OracleDriver());
      Connection cnn = DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","wisdom22");
      String nm=t1.getText();
       String user=t2.getText();
       String q="delete from facultyInfo where name='"+nm+"'";
       String q1="delete from userids where username='"+user+"'";
        st=cnn.createStatement();
       st.executeUpdate(q);
      st.executeQuery(q1);
       JOptionPane.showMessageDialog(null, "deleted");
      
       
        } catch (Exception e) {
           System.out.print(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
         count++;
        if(count%2==1)
        {
            t3.setEchoChar((char)0);
        }
        else
        {
            t3.setEchoChar('*');
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        admin a= new admin();
        a.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signupfaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signupfaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signupfaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signupfaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signupfaculty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JPasswordField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    // End of variables declaration//GEN-END:variables
}
