/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject;

/**
 *
 * @author hp
 */
import java.sql.*;
import javax.swing.JOptionPane;
import oracle.jdbc.driver.*;

public class SIGNUP2 extends javax.swing.JFrame {

    /**
     * Creates new form SIGNUP2
     */
     Connection cnn;
    Statement st;
    String gen;
   ResultSet rs;
    public SIGNUP2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        t9 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel2.setText("STUDENT REGISTRATION");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 10, 440, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("FULL NAME");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 70, 100, 30);
        jPanel1.add(t1);
        t1.setBounds(150, 70, 200, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("FATHER'S NAME");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 110, 140, 30);
        jPanel1.add(t3);
        t3.setBounds(150, 110, 200, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("ROLL NUMBER");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(360, 70, 120, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("PHONE NUMBER");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(360, 110, 140, 30);
        jPanel1.add(t2);
        t2.setBounds(490, 70, 200, 30);
        jPanel1.add(t4);
        t4.setBounds(500, 110, 190, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("GENDER");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 230, 80, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("MALE");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(150, 230, 70, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("FEMALE");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(240, 230, 80, 23);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("EMAIL");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 270, 60, 30);

        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });
        jPanel1.add(t8);
        t8.setBounds(90, 270, 530, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("ADDRESS");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 310, 80, 30);
        jPanel1.add(t9);
        t9.setBounds(90, 310, 600, 30);

        b1.setBackground(new java.awt.Color(255, 153, 255));
        b1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        b1.setText("REGISTER");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(130, 350, 110, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("COURSE");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 150, 120, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("BRANCH");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 190, 110, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("ADHARCARD NUMBER");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(350, 150, 180, 30);
        jPanel1.add(t5);
        t5.setBounds(530, 150, 170, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("SESSION");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(370, 190, 90, 30);
        jPanel1.add(t6);
        t6.setBounds(460, 190, 190, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Btech", "Mtech", "Phd", "B.Sc", "M.Sc" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(150, 150, 190, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSE", "ECE", "ICE", "Mechanical", "Civil", "Industrial Production", "Chemical", "BioTech", "IT" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(150, 190, 190, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("D.O.B");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(380, 230, 70, 20);
        jPanel1.add(t7);
        t7.setBounds(460, 230, 190, 30);

        jButton1.setBackground(new java.awt.Color(255, 153, 255));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 350, 100, 40);

        jButton2.setBackground(new java.awt.Color(255, 153, 255));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(250, 350, 120, 40);

        jButton3.setBackground(new java.awt.Color(255, 153, 255));
        jButton3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton3.setText("SEARCH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(380, 350, 120, 40);

        jButton4.setBackground(new java.awt.Color(255, 153, 255));
        jButton4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton4.setText("DELETE RECORD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(510, 350, 170, 40);

        jButton5.setBackground(new java.awt.Color(255, 153, 255));
        jButton5.setText("back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(10, 20, 55, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/courses backg.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t8ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        try {
             DriverManager.registerDriver(new OracleDriver());
      Connection cnn = DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","wisdom22");
      
      String nm=t1.getText();
      String rn=t2.getText();
      String fn=t3.getText();
      String cont=t4.getText();
      String num=t5.getText(); 
       String session=t6.getText();
      String dob=t7.getText();
      String email=t8.getText();
      String addr=t9.getText(); 
     if(jRadioButton1.isSelected()==true)
     {
          gen="male";
     }
     if(jRadioButton2.isSelected()==true)
     {
         gen="female";
     }
      String course = jComboBox1.getSelectedItem().toString();
      String branch = jComboBox2.getSelectedItem().toString();
      
       if(t1.getText().equals("") || t2.getText().equals("") || t3.getText().equals("") ||t4.getText().equals("") ||t5.getText().equals("") ||t6.getText().equals("") ||t7.getText().equals("")||t8.getText().equals("")||t9.getText().equals("") )
      {
       JOptionPane.showMessageDialog(null, "please fill all fields");
      }
      else if(cont.length()!=10)
              {
                  JOptionPane.showMessageDialog(null, "please fill valid contact details");
              }
      else if(num.length()!=12)
      {
           JOptionPane.showMessageDialog(null, "please fill valid adharcard number");
      }
       else if(addr.length()<10)
      {
           JOptionPane.showMessageDialog(null, "please fill complete address as on registered documents");
      }
        else if(email.length()<10)
      {
           JOptionPane.showMessageDialog(null, "please fill valid email address");
      }
     
      else
        {
      String q="insert into studentInfo values('"+nm+"','"+rn+"','"+fn+"','"+cont+"','"+course+"','"+branch+"','"+num+"','"+session+"','"+gen+"','"+dob+"','"+email+"','"+addr+"')";
      
      
       st=cnn.createStatement();
       st.executeUpdate(q);
      
       JOptionPane.showMessageDialog(null, "saved");
      
        }
        } catch (Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         t1.setText("");
        t2.setText("");
        t3.setText("");
        t4.setText("");
        t5.setText("");
        t6.setText("");
        t7.setText("");
        t8.setText("");
        t9.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            
            DriverManager.registerDriver(new OracleDriver());
      Connection cnn = DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","wisdom22");
      
      int rn=Integer.parseInt(t2.getText());
      String nm="";
      String fn="";
      String cont="";
      String course="";
      String branch="";
      String num="";
      String gen="";
      String session="";
      String dob="";
      String email="";
      String addr="";
      
      String q="select * from studentInfo where rollno='"+rn+"'";
      st=cnn.createStatement();
      rs=st.executeQuery(q);
      if(rs.next())
      {
          nm=rs.getString("name");
          fn=rs.getString("father");
          cont=rs.getString("contact");
          course=rs.getString("course");
          branch=rs.getString("branch");
          num=rs.getString("adharno");
          session=rs.getString("duration");
          gen=rs.getString("gender");
          dob=rs.getString("dob");
          email=rs.getString("email");
          addr=rs.getString("address");
           t1.setText(nm);
      t3.setText(fn);
      t4.setText(cont);
      t5.setText(num); 
      t6.setText(session);
      t7.setText(dob);
      t8.setText(email);
      t9.setText(addr); 
      if(gen.equals("male"))
      {
          jRadioButton1.setSelected(true);
      }
      if(gen.equals("female"))
      {
          jRadioButton2.setSelected(true);
      }
      jComboBox1.setSelectedItem(course);
      jComboBox2.setSelectedItem(branch);
      }
      else
      {
          JOptionPane.showMessageDialog(null,"record not found");
      }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            DriverManager.registerDriver(new OracleDriver());
      Connection cnn = DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","wisdom22");
      
      String nm=t1.getText();
      String rn=t2.getText();
      String fn=t3.getText();
      String cont=t4.getText();
      String num=t5.getText(); 
       String session=t6.getText();
      String dob=t7.getText();
      String email=t8.getText();
      String addr=t9.getText(); 
     if(jRadioButton1.isSelected()==true)
     {
          gen="male";
     }
     if(jRadioButton2.isSelected()==true)
     {
         gen="female";
     }
      String course = jComboBox1.getSelectedItem().toString();
      String branch = jComboBox2.getSelectedItem().toString();
      
      String q="update studentInfo set name='"+nm+"',father='"+fn+"',contact='"+cont+"',course='"+course+"',branch='"+branch+"',adharno='"+num+"',duration='"+session+"',gender='"+gen+"',dob='"+dob+"',email='"+email+"',address='"+addr+"' where rollno='"+rn+"'";
      
       st=cnn.createStatement();
       st.executeUpdate(q);
      
       JOptionPane.showMessageDialog(null, "updated");
      
        
        } catch (Exception e) {
            System.out.print(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        try {
             DriverManager.registerDriver(new OracleDriver());
      Connection cnn = DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","system","wisdom22");
      
       String rn=t2.getText();
       String q="delete from studentInfo where rollno='"+rn+"'";
        st=cnn.createStatement();
       st.executeUpdate(q);
      
       JOptionPane.showMessageDialog(null, "deleted");
      
       
        } catch (Exception e) {
           System.out.print(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        ACCOUNTANT a=new ACCOUNTANT();
        a.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIGNUP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIGNUP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIGNUP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIGNUP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIGNUP2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
